/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import java.util.Date;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author new
 */
public class ViewAllRecords extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecords
     */
    DefaultTableModel model; 
    public ViewAllRecords() {
        initComponents();
        clearTable();
        setDetailsTotable();
    }
    
    //setting details in table
    public void setDetailsTotable()
    {
        try{
            Connection con= DBConnection.getConnection();
            String sql="select * from issue_book_details";
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next())
            {
                String id=rs.getString("id");
                String bookName=rs.getString("book_name");
                String studentName=rs.getString("student_name");
                String issueDate=rs.getString("issue_date" );
                String dueDate=rs.getString("due_date");
                String status=rs.getString("status");
                
                Object[] obj={id,bookName,studentName,issueDate,dueDate,status};
                model=(DefaultTableModel) tbl_viewAllRecords.getModel();
                model.addRow(obj);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    //to fetch the recors between given dates
    public void search()
    {
        Date ufromDate=Date_FromDate.getDatoFecha();
        Date utoDate=Date_toDate.getDatoFecha();
        
        long l1=ufromDate.getTime();
        long l2=utoDate.getTime();
        
        java.sql.Date sfromDate=new java.sql.Date(l1);
        java.sql.Date stoDate=new java.sql.Date(l2);
        
        try
        {
            Connection con= DBConnection.getConnection();
            String sql="select * from issue_book_details where issue_date BETWEEN ? and ?";
            PreparedStatement pst= con.prepareStatement(sql);
            pst.setDate(1, sfromDate);
            pst.setDate(2, stoDate);
            
            ResultSet rs=pst.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "No Records Found");
            }
            else
            {
                    String id=rs.getString("id");
                    String bookName=rs.getString("book_name");
                    String studentName=rs.getString("student_name");
                    String issueDate=rs.getString("issue_date" );
                    String dueDate=rs.getString("due_date");
                    String status=rs.getString("status");

                    Object[] obj={id,bookName,studentName,issueDate,dueDate,status};
                    model=(DefaultTableModel) tbl_viewAllRecords.getModel();
                    model.addRow(obj);
                while(rs.next())
                {
//                    JOptionPane.showMessageDialog(this, "Inside");
                    id=rs.getString("id");
                    bookName=rs.getString("book_name");
                    studentName=rs.getString("student_name");
                    issueDate=rs.getString("issue_date" );
                    dueDate=rs.getString("due_date");
                    status=rs.getString("status");

                    Object[] obj1={id,bookName,studentName,issueDate,dueDate,status};
                    model=(DefaultTableModel) tbl_viewAllRecords.getModel();
                    model.addRow(obj1);
                }
                
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    //Clear the table
    public void clearTable()
    {
         model=(DefaultTableModel) tbl_viewAllRecords.getModel();
         model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Date_FromDate = new rojeru_san.componentes.RSDateChooser();
        Date_toDate = new rojeru_san.componentes.RSDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showALL = new necesario.RSMaterialButtonCircle();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Search_Records = new necesario.RSMaterialButtonCircle();
        Panel_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewAllRecords = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:/Users/new/Documents/NetBeansProjects/Library_Management_System/src/main/java/AddNewBookIcons/icons8_Literature_100px_1.png"));
        jLabel11.setText("View All Records");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 300, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 360, 5));

        Date_FromDate.setColorBackground(new java.awt.Color(255, 51, 51));
        Date_FromDate.setColorForeground(new java.awt.Color(255, 51, 51));
        Date_FromDate.setPlaceholder("Select  issue date");
        jPanel1.add(Date_FromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 260, -1));

        Date_toDate.setColorBackground(new java.awt.Color(255, 51, 51));
        Date_toDate.setColorForeground(new java.awt.Color(255, 51, 51));
        Date_toDate.setPlaceholder("Select  issue date");
        jPanel1.add(Date_toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 260, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("From:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        showALL.setBackground(new java.awt.Color(102, 102, 102));
        showALL.setText("ALL");
        showALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showALLActionPerformed(evt);
            }
        });
        jPanel1.add(showALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 190, 170, 60));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:/Users/new/Documents/NetBeansProjects/Library_Management_System/src/main/java/AddNewBookIcons/icons8_Rewind_48px.png"));
        jLabel17.setText("BACK");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("x");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 0, 80, 40));

        Search_Records.setBackground(new java.awt.Color(255, 51, 51));
        Search_Records.setText("Search");
        Search_Records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_RecordsActionPerformed(evt);
            }
        });
        jPanel1.add(Search_Records, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 170, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 280));

        Panel_Table.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_viewAllRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_viewAllRecords.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        tbl_viewAllRecords.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_viewAllRecords.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_viewAllRecords.setRowHeight(25);
        tbl_viewAllRecords.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tbl_viewAllRecords);

        Panel_Table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 1210, 430));

        getContentPane().add(Panel_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1500, 580));

        setSize(new java.awt.Dimension(1500, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        HomePage home = null;
        try {
            home = new HomePage();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageStudents.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void showALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showALLActionPerformed
        clearTable();
        setDetailsTotable();
    }//GEN-LAST:event_showALLActionPerformed

    private void Search_RecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_RecordsActionPerformed
        // TODO add your handling code here:
        if(Date_FromDate.getDatoFecha()!=null && Date_toDate.getDatoFecha()!=null)
        {
             clearTable();
            search();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"please select date");
        }
       
    }//GEN-LAST:event_Search_RecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser Date_FromDate;
    private rojeru_san.componentes.RSDateChooser Date_toDate;
    private javax.swing.JPanel Panel_Table;
    private necesario.RSMaterialButtonCircle Search_Records;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle showALL;
    private rojeru_san.complementos.RSTableMetro tbl_viewAllRecords;
    // End of variables declaration//GEN-END:variables
}
